---
- hosts: webservers 
  become: True
  tasks:
    - name: Copy file to host
      copy:
        src: target/helloworld-0.0.1-SNAPSHOT.jar
        dest: /home/ec2-user/app/
    - name: Start java app
      shell: |
        java -jar target/helloworld-0.0.1-SNAPSHOT.jar
